[mypy]
python_version = 3.11
exclude = (?x)(^server/\.venv/|^server/migrations/)

[mypy-flask_cors]
ignore_missing_imports = True

[mypy-transformers.*]
ignore_missing_imports = True

[mypy-torch.*]
ignore_missing_imports = True

[mypy-onnxruntime.*]
ignore_missing_imports = True

[mypy-optimum.*]
ignore_missing_imports = True

[mypy-youtube_transcript_api.*]
ignore_missing_imports = True
